sudo: false
env:
  global:
    - LD_LIBRARY_PATH=/home/travis/build/jeremyletang/rust-sfml/sfml_install/usr/local/lib
language: rust
script:
  - mkdir sfml_install
  - wget http://www.sfml-dev.org/files/SFML-2.3.2-sources.zip
  - unzip -q SFML-2.3.2-sources.zip
  - pushd SFML-2.3.2 && mkdir build && cd build && cmake .. && make
  - make DESTDIR=/home/travis/build/jeremyletang/rust-sfml/sfml_install install
  - popd
  - wget http://www.sfml-dev.org/files/CSFML-2.3-sources.zip
  - unzip -q CSFML-2.3-sources.zip
  - pushd CSFML-2.3
  - mkdir cmake/Modules
  - cp /home/travis/build/jeremyletang/rust-sfml/sfml_install/usr/local/share/SFML/cmake/Modules/FindSFML.cmake cmake/Modules
  - mkdir build && cd build && cmake -DSFML_ROOT=/home/travis/build/jeremyletang/rust-sfml/sfml_install/usr/local .. && make
  - make DESTDIR=/home/travis/build/jeremyletang/rust-sfml/sfml_install install
  - popd
  - mkdir .cargo
  - mv .travis.cargo.config .cargo/config
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
addons:
  apt:
    packages:
    - libpthread-stubs0-dev
    - libgl1-mesa-dev
    - libx11-dev
    - libx11-xcb-dev
    - libxrandr-dev
    - libfreetype6-dev
    - libglew-dev
    - libjpeg8-dev
    - libgpgme11-dev
    - libsndfile1-dev
    - libopenal-dev
    - libjpeg62
    - cmake
